name: Linting and Formatting on PR/PUSH

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying to prod
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > sagar.pem
          chmod 600 sagar.pem  # Secure the private key
          
          ssh -i sagar.pem -o StrictHostKeyChecking=no ubuntu@13.53.198.45 << 'EOF'
            cd truborepo-test1/
            git pull
            
            # Load NVM
            source ~/.bashrc
            # Ensure pnpm is installed
            command -v pnpm || npm install -g pnpm

            # Run build in background to prevent SSH timeout
            nohup pnpm install > install.log 2>&1 &
            wait
            nohup pnpm run build > build.log 2>&1 &
            wait

            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
