name: Linting and Formatting on PR/PUSH

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying to prod
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > sagar.pem
          chmod 600 sagar.pem  # Secure the private key
          
          ssh -i sagar.pem -o StrictHostKeyChecking=no ubuntu@13.49.64.17 << 'EOF'
            cd truborepo-test1/
            git pull
            
            export PATH=/home/ubuntu/.nvm/versions/node/v22.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
            command -v pnpm || npm install -g pnpm

            pmpm run build 
            pm2 restart web
            pm2 restart http-server
            pm2 restart ws-server
          EOF
