name: Linting and Formatting on PR/PUSH

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying to prod
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > sagar.pem
          chmod 600 sagar.pem  # Secure the private key
          
          ssh -i sagar.pem -o StrictHostKeyChecking=no ubuntu@51.20.76.69 << 'EOF'
            npm
            cd truborepo-test1/
            npm
          EOF
