name: Linting and formating on PR/PUSH

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
        - "main"

  
jobs:
  redeploy_everything:
    name: Deploying to prod
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server
        run: |
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/sagar.pem
         ssh -i ~/sagar.pem ubuntu@51.20.76.69
         cd truborepo-test1/ && git pull 
         pnpm install 
         pnpm run build
         pm2 restart fe-server
         pm2 restart http-server
         pm2 restart ws-server  


    
